"""failed prev so create tables

Revision ID: 17aed2f58aa6
Revises: e26b28aa9f4f
Create Date: 2026-03-24 22:33:07.716972

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17aed2f58aa6'
down_revision: Union[str, None] = 'e26b28aa9f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('CusId', sa.Integer(), nullable=False),
    sa.Column('CusName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CusAddress', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CusEmail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('CusPhone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('CusId')
    )
    op.create_table('dinespace',
    sa.Column('DinespaceId', sa.Integer(), nullable=False),
    sa.Column('DinespaceName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('DinespaceId')
    )
    op.create_table('dinetable',
    sa.Column('DineTableId', sa.Integer(), nullable=False),
    sa.Column('IsWorkingCondition', sa.Boolean(), nullable=False),
    sa.Column('IsCustomerOccupied', sa.Boolean(), nullable=False),
    sa.Column('Dinespace_FId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('DineTableId')
    )
    op.create_table('orders',
    sa.Column('OrderId', sa.Integer(), nullable=False),
    sa.Column('Customer_FId', sa.Integer(), nullable=True),
    sa.Column('Dinetable_FId', sa.Integer(), nullable=True),
    sa.Column('Transaction_FId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('OrderTimeStamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('OrderId')
    )
    op.create_table('qr',
    sa.Column('QrId', sa.Integer(), nullable=False),
    sa.Column('Qrstring', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Dinetable_FId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('QrId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr')
    op.drop_table('orders')
    op.drop_table('dinetable')
    op.drop_table('dinespace')
    op.drop_table('customer')
    # ### end Alembic commands ###
