"""made food image tables and added food 

Revision ID: 2b095875c4d4
Revises: 442650ea897a
Create Date: 2026-04-05 14:01:06.244964

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b095875c4d4'
down_revision: Union[str, None] = '442650ea897a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customersession',
    sa.Column('CustomerSession', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Qr_Fid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('CustomerSession')
    )
    op.create_table('foodimage',
    sa.Column('FoodImageId', sa.Integer(), nullable=False),
    sa.Column('Food_FId', sa.Integer(), nullable=True),
    sa.Column('FoodImageFileName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('FoodImagePath_Fid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['FoodImagePath_Fid'], ['food.FoodId'], ),
    sa.ForeignKeyConstraint(['Food_FId'], ['food.FoodId'], ),
    sa.PrimaryKeyConstraint('FoodImageId')
    )
    op.create_table('foodimagespath',
    sa.Column('FoodImagesPathId', sa.Integer(), nullable=False),
    sa.Column('FoodImagesPathName', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('FoodImagesPathId')
    )
    op.drop_table('price')
    op.add_column('food', sa.Column('FoodImage_FId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'food', 'foodimage', ['FoodImage_FId'], ['FoodImageId'])
    op.add_column('qr', sa.Column('QrBodyUrlId', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr', 'QrBodyUrlId')
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.drop_column('food', 'FoodImage_FId')
    op.create_table('price',
    sa.Column('PriceId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('PriceId', name='price_pkey')
    )
    op.drop_table('foodimagespath')
    op.drop_table('foodimage')
    op.drop_table('customersession')
    # ### end Alembic commands ###
