"""make foreign keys

Revision ID: 36b3682388cb
Revises: 17aed2f58aa6
Create Date: 2026-03-24 22:40:36.687636

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b3682388cb'
down_revision: Union[str, None] = '17aed2f58aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dinetable', 'dinespace', ['Dinespace_FId'], ['DinespaceId'])
    op.create_foreign_key(None, 'orders', 'customer', ['Customer_FId'], ['CusId'])
    op.create_foreign_key(None, 'orders', 'dinetable', ['Dinetable_FId'], ['DineTableId'])
    op.create_foreign_key(None, 'qr', 'dinetable', ['Dinetable_FId'], ['DineTableId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qr', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'dinetable', type_='foreignkey')
    # ### end Alembic commands ###
