"""FoodPricing Added, Price Table Deprecated For Test

Revision ID: 67d0fe6fc168
Revises: 7d375280ef12
Create Date: 2026-03-28 18:12:42.243585

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d0fe6fc168'
down_revision: Union[str, None] = '7d375280ef12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('is_customizable', sa.Boolean(), nullable=False))
    op.add_column('food', sa.Column('FoodPricing', sa.JSON(), nullable=True))
    op.drop_constraint('food_Price_FId_fkey', 'food', type_='foreignkey')
    op.drop_column('food', 'Price_FId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('Price_FId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('food_Price_FId_fkey', 'food', 'price', ['Price_FId'], ['PriceId'])
    op.drop_column('food', 'FoodPricing')
    op.drop_column('food', 'is_customizable')
    # ### end Alembic commands ###
