"""adding columns

Revision ID: 6ef07a9a5ab2
Revises: 92c5e443f530
Create Date: 2026-03-14 16:23:23.622203

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef07a9a5ab2'
down_revision: Union[str, None] = '92c5e443f530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('FoodName', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('food', sa.Column('FoodRegionalType_FId', sa.Integer(), nullable=True))
    op.add_column('food', sa.Column('FoodAllergenComment', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('food', sa.Column('FoodAlert', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('food', sa.Column('IsAvailable', sa.Boolean(), nullable=False))
    op.add_column('food', sa.Column('Price_FId', sa.Integer(), nullable=True))
    op.add_column('foodregionaltype', sa.Column('FoodRegionalTypeName', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('price', sa.Column('Value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'Value')
    op.drop_column('foodregionaltype', 'FoodRegionalTypeName')
    op.drop_column('food', 'Price_FId')
    op.drop_column('food', 'IsAvailable')
    op.drop_column('food', 'FoodAlert')
    op.drop_column('food', 'FoodAllergenComment')
    op.drop_column('food', 'FoodRegionalType_FId')
    op.drop_column('food', 'FoodName')
    # ### end Alembic commands ###
