"""adding foreignkeys

Revision ID: 8f665c4588a1
Revises: 6ef07a9a5ab2
Create Date: 2026-03-14 16:26:00.425848

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f665c4588a1'
down_revision: Union[str, None] = '6ef07a9a5ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'food', 'foodregionaltype', ['FoodRegionalType_FId'], ['FoodRegionalTypeId'])
    op.create_foreign_key(None, 'food', 'price', ['Price_FId'], ['PriceId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.drop_constraint(None, 'food', type_='foreignkey')
    # ### end Alembic commands ###
