"""empty message

Revision ID: 92c5e443f530
Revises: 
Create Date: 2026-03-14 16:17:54.600712

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c5e443f530'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('FoodId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('FoodId')
    )
    op.create_table('foodregionaltype',
    sa.Column('FoodRegionalTypeId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('FoodRegionalTypeId')
    )
    op.create_table('price',
    sa.Column('PriceId', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('PriceId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price')
    op.drop_table('foodregionaltype')
    op.drop_table('food')
    # ### end Alembic commands ###
