"""remove food back foreignkey 

Revision ID: d89c912ff59c
Revises: fed9fcd25f14
Create Date: 2026-05-03 12:34:24.106249

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd89c912ff59c'
down_revision: Union[str, None] = 'fed9fcd25f14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foodimage', 'Food_FId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foodimage', sa.Column('Food_FId', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
