"""remove food back foreignkey 

Revision ID: fed9fcd25f14
Revises: 2b095875c4d4
Create Date: 2026-05-03 12:30:09.371156

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed9fcd25f14'
down_revision: Union[str, None] = '2b095875c4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('foodimage_Food_FId_fkey', 'foodimage', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('foodimage_Food_FId_fkey', 'foodimage', 'food', ['Food_FId'], ['FoodId'])
    # ### end Alembic commands ###
